export const metadata = {
  title: 'URL Shortener',
  description: 'Generated by Andres Soler, shorten your URLs easily',
}

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body>{children}</body>
    </html>
  )
}
